tag: "MTS_Dialog_Sample"

summarizer:
  spec:
    - provider: "openai"
      checkpoint: "openai/gpt-4.1-nano-2025-04-14"
      endpoint: "https://api.openai.com/v1/chat/completions"
    - provider: "openrouter"
      checkpoint: "qwen/qwen3-32b:free"
      endpoint: "https://openrouter.ai/api/v1"
    - provider: "openrouter"
      checkpoint: "qwen/qwen3-14b:free"
      endpoint: "https://openrouter.ai/api/v1"
    - provider: "openrouter"
      checkpoint: "qwen/qwen3-8b:free"
      endpoint: "https://openrouter.ai/api/v1"

pseudo-labeler:
  spec:
    - provider: "openai"
      checkpoint: "openai/gpt-4.1-mini-2025-04-14"
      endpoint: "https://api.openai.com/v1/chat/completions"

judge-llm:
  spec:
    - provider: "openai"
      checkpoint: "openai/gpt-4.1-mini-2025-04-14"
      endpoint: "https://api.openai.com/v1/chat/completions"
    # - provider: "openrouter"
    #   checkpoint: "qwen/qwen3-32b:free"
    #   endpoint: "https://openrouter.ai/api/v1"
    # - provider: "openrouter"
    #   checkpoint: "qwen/qwen3-14b:free"
    #   endpoint: "https://openrouter.ai/api/v1"
    # - provider: "openrouter"
    #   checkpoint: "qwen/qwen3-8b:free"
    #   endpoint: "https://openrouter.ai/api/v1"

input_paths:
  MTS-Dialog-Sampled-10: "data/sampled/MTS-Dialog.csv"

output_paths:
  transcript: "data/processed/(1)_transcript"
  keyfact: "data/processed/(2)_keyfact"
  summary: "data/processed/(3)_summary"
  factuality: "data/processed/(4)_factuality"
  alignment: "data/processed/(5)_alignment"
  finesure_pipeline: "output/finesure_pipeline_output"
  finesure_result: "output/finesure_result"

logging:
  level: "INFO"