run_name: "gpt4_summary_run"

model:
  name: "gpt-4"
  endpoint: "https://api.openai.com/v1/chat/completions"
  api_key: "your-api-key"
  parameters:
    temperature: 0.7
    max_tokens: 512

output:
  directory: "sample/gpt4"
  save_format: "json"

logging:
  level: "INFO"